@LAZYGLOBAL ON.
DECLARE PARAMETER TargetApKm.
SET running TO TRUE.

SET WarpStopTime TO 30. //custom value 

SET TargetAp TO TargetApKm*1000.

CLEARSCREEN.

//display info
WHEN TRUE THEN {
	IF NOT running {
		// cleanup
	} ELSE {
	PRINT "Apoapsis: "+ROUND(APOAPSIS)+" m       " AT (0,2).
	PRINT "Target apoapsis: "+ROUND(TargetAp)+" m       " AT (0,3).
	PRINT "Time to periapsis: "+ROUND(ETA:PERIAPSIS)+"s       " AT (0,4).
	PRINT "Running: uChangeAp" AT (0,6).
    PRESERVE.
	}
}


RCS ON.
SAS OFF.

//staging
SET InitialStageThrust TO MAXTHRUST.
WHEN TRUE THEN {
	IF NOT running {
		// cleanup
	} ELSE IF MAXTHRUST < InitialStageThrust {
	WAIT 1.
	STAGE.
		IF MAXTHRUST > 0 {
		SET InitialStageThrust TO MAXTHRUST.
	}
	PRESERVE.
	} ELSE {
		PRESERVE.
	}
}


IF TargetAp = APOAPSIS {
    SET running TO FALSE.
}

IF TargetAp < APOAPSIS AND running = TRUE{
	SET PeV TO (2*BODY:MU*((1/(BODY:RADIUS+PERIAPSIS))-(1/ORBIT:semimajoraxis/2)))^0.5.
	SET TPeV TO (2*BODY:MU*((1/(BODY:RADIUS+PERIAPSIS))-(1/(TargetAp+PERIAPSIS+BODY:RADIUS*2))))^0.5.
	SET BurnDeltaV TO PeV-TPeV.
	SET BurnTime TO (BurnDeltaV*MASS)/AVAILABLETHRUST.

	WAIT 1.
    LOCK STEERING TO RETROGRADE.
	SET WARPMODE TO "rails".
	PRINT "Warping to periapsis" AT (0,0).
	SET BurnMoment TO TIME:SECONDS + ETA:PERIAPSIS.
	WARPTO(BurnMoment-BurnTime/2-WarpStopTime).

	WAIT UNTIL VANG(SHIP:FACING:FOREVECTOR,STEERING:FOREVECTOR) <  5 AND TIME:SECONDS > BurnMoment-BurnTime/2.
		LOCK THROTTLE TO 1.
		PRINT "Burn started        " AT (0,0).

	WAIT UNTIL SHIP:VELOCITY:ORBIT:MAG < TPeV.
		LOCK THROTTLE TO 0.
		PRINT "Burn completed" AT (0,0).

	SET running TO FALSE.
	UNLOCK STEERING.
	LOCK THROTTLE TO 0. UNLOCK THROTTLE.
	CLEARSCREEN.
}

IF TargetAp > APOAPSIS AND running = TRUE{
	SET PeV TO (2*BODY:MU*((1/(BODY:RADIUS+PERIAPSIS))-(1/ORBIT:semimajoraxis/2)))^0.5.
	SET TPeV TO (2*BODY:MU*((1/(BODY:RADIUS+PERIAPSIS))-(1/(TargetAp+PERIAPSIS+BODY:RADIUS*2))))^0.5.
	SET BurnDeltaV TO TPeV-PeV.
	SET BurnTime TO (BurnDeltaV*MASS)/AVAILABLETHRUST.
		
	WAIT 1.
    LOCK STEERING TO PROGRADE.
	SET WARPMODE TO "rails".
	PRINT "Warping to periapsis" AT (0,0).
	SET BurnMoment TO TIME:SECONDS + ETA:PERIAPSIS.
	WARPTO(BurnMoment-BurnTime/2-WarpStopTime).

	WAIT UNTIL VANG(SHIP:FACING:FOREVECTOR,STEERING:FOREVECTOR) <  5 AND TIME:SECONDS > BurnMoment-BurnTime/2.
		LOCK THROTTLE TO 1.
		PRINT "Burn started        " AT (0,0).

	WAIT UNTIL SHIP:VELOCITY:ORBIT:MAG > TPeV.
		LOCK THROTTLE TO 0.
		PRINT "Burn completed" AT (0,0).

	SET running TO FALSE.
	UNLOCK STEERING.
	LOCK THROTTLE TO 0. UNLOCK THROTTLE.
	CLEARSCREEN.
}

RCS OFF.
SAS ON.
SET running TO FALSE.
SET SHIP:CONTROL:PILOTMAINTHROTTLE TO 0.
CLEARSCREEN.