@LAZYGLOBAL ON.
DECLARE PARAMETER TargetPeKm.
SET running TO TRUE.

SET WarpStopTime TO 30. //custom value 

SET TargetPe TO TargetPeKm*1000.

CLEARSCREEN.

//display info
WHEN TRUE THEN {
	IF NOT running {
		// cleanup
	} ELSE {
	PRINT "Periapsis: "+ROUND(PERIAPSIS)+" m       " AT (0,2).
	PRINT "Target periapsis: "+ROUND(TargetPe)+" m       " AT (0,3).
	PRINT "Time to apoapsis: "+ROUND(ETA:APOAPSIS)+"s       " AT (0,4).
	PRINT "Running: uChangePe" AT (0,6).
    PRESERVE.
	}
}



RCS ON.
SAS OFF.

//staging
SET InitialStageThrust TO MAXTHRUST.
WHEN TRUE THEN {
	IF NOT running {
		// cleanup
	} ELSE IF MAXTHRUST < InitialStageThrust {
	WAIT 1.
	STAGE.
		IF MAXTHRUST > 0 {
		SET InitialStageThrust TO MAXTHRUST.
	}
	PRESERVE.
	} ELSE {
		PRESERVE.
	}
}


IF TargetPe = PERIAPSIS {
    SET running TO FALSE.
}

IF TargetPe < PERIAPSIS AND running = TRUE{
	SET ApV TO (2*BODY:MU*((1/(BODY:RADIUS+APOAPSIS))-(1/ORBIT:semimajoraxis/2)))^0.5.
	SET TApV TO (2*BODY:MU*((1/(BODY:RADIUS+APOAPSIS))-(1/(TargetPe+APOAPSIS+BODY:RADIUS*2))))^0.5.
	SET BurnDeltaV TO ApV-TApV.
	SET BurnTime TO (BurnDeltaV*MASS)/AVAILABLETHRUST.

	WAIT 1.
	LOCK STEERING TO RETROGRADE.
	SET WARPMODE TO "rails".
	PRINT "Warping to apoapsis" AT (0,0).
	SET BurnMoment TO TIME:SECONDS + ETA:APOAPSIS.
	WARPTO(BurnMoment-BurnTime/2-WarpStopTime).

	WAIT UNTIL VANG(SHIP:FACING:FOREVECTOR,STEERING:FOREVECTOR) <  5 AND TIME:SECONDS > BurnMoment-BurnTime/2.
		LOCK THROTTLE TO 1.
		PRINT "Burn started        " AT (0,0).

	WAIT UNTIL SHIP:VELOCITY:ORBIT:MAG < TApV.
		LOCK THROTTLE TO 0.
		PRINT "Burn completed" AT (0,0).

	SET running TO FALSE.
	UNLOCK STEERING.
	LOCK THROTTLE TO 0. UNLOCK THROTTLE.
	CLEARSCREEN.
}

IF TargetPe > PERIAPSIS AND running = TRUE{
	SET ApV TO (2*BODY:MU*((1/(BODY:RADIUS+APOAPSIS))-(1/ORBIT:semimajoraxis/2)))^0.5.
	SET TApV TO (2*BODY:MU*((1/(BODY:RADIUS+APOAPSIS))-(1/(TargetPe+APOAPSIS+BODY:RADIUS*2))))^0.5.
	SET BurnDeltaV TO TApV-ApV.
	SET BurnTime TO (BurnDeltaV*MASS)/AVAILABLETHRUST.
		
	WAIT 1.
	LOCK STEERING TO PROGRADE.
	SET WARPMODE TO "rails".
	PRINT "Warping to apoapsis" AT (0,0).
	SET BurnMoment TO TIME:SECONDS + ETA:APOAPSIS.
	WARPTO(BurnMoment-BurnTime/2-WarpStopTime).

	WAIT UNTIL VANG(SHIP:FACING:FOREVECTOR,STEERING:FOREVECTOR) <  5 AND TIME:SECONDS > BurnMoment-BurnTime/2.
		LOCK THROTTLE TO 1.
		PRINT "Burn started        " AT (0,0).

	WAIT UNTIL SHIP:VELOCITY:ORBIT:MAG > TApV.
		LOCK THROTTLE TO 0.
		PRINT "Burn completed" AT (0,0).

	SET running TO FALSE.
	UNLOCK STEERING.
	LOCK THROTTLE TO 0. UNLOCK THROTTLE.
	CLEARSCREEN.
}

RCS OFF.
SAS ON.
SET running TO FALSE.
SET SHIP:CONTROL:PILOTMAINTHROTTLE TO 0.
CLEARSCREEN.